### ISSUE TITLE
How to force a character to use a province as his capital ?

### ISSUE THREAD

**Issue by Athoen974** [Middle-Earth-Project-Team/mod#101]
Arnor :
•At FoA start, the actual capital of Arthedain is Emyn Uial (north to Annuminas),It should be Fornost but the king do not use it as so.
I CAN'T FIND HOW TO CHANGE THIS

This would be usefull for other characters in Cardolan having tribal and feudal holdings : if they set their capital in a tribal province, they become tribel even if we do not want them to.

**Comment by Lonhaldar** [comment]
I tried to use the "capital = c_fornost" in history/characters command, but it doesn't works.

**Comment by Lonhaldar** [comment]
Well, i was able to make it by changing a little thing : 
in MEP_startup, i added these lines in the first event (triggered at start of a new game) : 
	
	immediate = {
		if = {
			limit = {
				year = 9204
				NOT = { year = 11362 }
				has_landed_title = k_arthedain
				has_landed_title = c_fornost
			}
			hidden_tooltip = {
				b_citadel_fornost = { province_capital = yes }
				ROOT = {
					b_citadel_fornost = {
							usurp_title = PREV
						}
					}
				b_citadel_fornost = { 
					ROOT = { capital = PREV }
				}
			}			
		}
	}

With these lines, the capital is automatically changed to Fornost. I tested it, it works well!
