### ISSUE TITLE
Gwaith i Mirdain in Ost-in-Edhil

### ISSUE THREAD

**Issue by Athoen974** [Middle-Earth-Project-Team/mod#102]
Is this supposed to be a unique building ? If so I will make it available in the capital barony only.
If this is a more of a global fortress like Caras-Galadhon or Thranduil's Halls, I should add it to cities also BUT the income is really huge : I do not think any other single buildings as this.

**Comment by Lonhaldar** [comment]
I agree, only for the capital barony will be better!

**Comment by Lonhaldar** [comment]
Fixed!
