### ISSUE TITLE
Witch King being bankrupt too easily : cost of orc army

### ISSUE THREAD

**Issue by Athoen974** [Middle-Earth-Project-Team/mod#104]
The huge numbers if the witch King's army makes are mostly based upon his own levy, and therefore have an important cost (16/month) while his own revenue is much lower. So after 1 petty war he is ruined and can't do much.
I intend to add an important tax income to his fortress so counterbalance this but I Wonder if we could lower the cost for orcish armies : a 1000 orc army being weaker than a 1000 dwarf army, it should cost much less.

**Comment by Lonhaldar** [comment]
Well, i prefer the solution to give some income bonuses than lower the size of orkish armies!

**Comment by Athoen974** [comment]
The idea is to decrease the cost of orc amy, not its size. But can that be done Lon ?

**Comment by Lonhaldar** [comment]
I never seen something like this.
But we can go around this with a small event, triggered when orcs are at war, who'll give a bonus of income during the war? Could be with a "monthly_character_wealth = 9.0" for exemple, "global_tax_modifier = 2.0" or "tax_income = 5.0". The first one will be easier to balance i think. The point is to don't forget to remove this at peace ^^

**Comment by RiccoPT** [comment]
this can be done with an trigered modifier 
a little heavy on memory needs to be tested but
orc_army = {
	potential = {
		is_ruler = yes
		war = yes
		OR = {
			culture_group = culture_group_melkor
			AND = {
				culture_group = culture_group_melkor
				trait = evil_side
			}
		}		
	}	
	trigger = {
		always = yes
	}
	global_tax_modifier = 5 // change according to tier or wealth 
}

**Comment by Lonhaldar** [comment]
Looks interesting, maybe can we make it as events as well, adding an idea that "finally you're at war, and all your demesne should work for your glory. Lash your slaves harder, and they'll produce more weapons and foods for your army. Will you do it?"

**Comment by RiccoPT** [comment]
OK will add both event and triggered modfier

**Comment by Lonhaldar** [comment]
good :)

**Comment by RiccoPT** [comment]
Already added the modifier,in my opinion there is no need for a event, the way I saw was a trigger modifier that starts when you have less then 500 gold and are at war.
Let me know is you think it needs an event i just belive it will pop up to offen and be heavy on low PC's.
An event could be created when you start a war so it can be balanced out in other ways.

**Comment by RiccoPT** [comment]
working just needs to be balanced out in a war melkor group and sauron never will be bankrupt
