### ISSUE TITLE
Add casus belli/join war for Good Races

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#106]
No way currently for Good Races to join in war against Sauron or attack him generally

**Comment by Lonhaldar** [comment]
Added some little things : 
- Now, a character at war with Sauron will have a chance to call the White Council to gather a "Great Alliance of Free Peoples".
- "Good" Independant Rulers will then be called, and will choose to join or not the alliance. If they don't, they'll lost their "Guardian of Free Peoples" trait.
- The White Council can choose to reject the alliance.

It'll help us to simulate massive wars between Sauron and the Free Peoples!

**Comment by Lonhaldar** [comment]
- If the Free Peoples are making a great Alliance, Sauron will command all the evil forces to join his war too. They won't have any choice, it's an order from the Dark Lord ^^

- Any human character will be able to join independantly a War between Sauron and a "Good" Realm by a decision.
