### ISSUE TITLE
Himling event

### ISSUE THREAD

**Issue by Athoen974** [Middle-Earth-Project-Team/mod#109]
- Decision icon has no desc localisation (it has title loc)

- Event fires no-stop as soon as I conquer the island, I do not have to click on the decision icon

- with decision icon, there is no cost, no duration, so this is just clicking untill having the reward.
There is no reason why a character could not search as many times as he wants, but there should be a cost (gold for trying, and prestige loss for finding nothing)
The whole event should take a few weeks with a timer preventing to go back immediatly (once a year ?)

- By the way I only got the sword, but never the armor.

- Himling sword does not appear in the list of the artifacts

**Comment by Lonhaldar** [comment]
- Choose to push the decision will now cost 75 cash, 100 prestige and 50 piety.
- If you've got one of the items, you can't search anymore in the ruins, so you won't be able to find/search for the other one.
- The event chain will now take two months.
- Fixed the bug with the non-stop events

All works fine now! :)
