### ISSUE TITLE
artifacts not passed on after abdicating the throne

### ISSUE THREAD

**Issue by Athoen974** [Middle-Earth-Project-Team/mod#112]
Just got  my arnorian king incapable... so with a regent.
AND with many holdings being built, that makes many titles I can't give away, so game more or less broken at that point. We the lifespan of an heir of Isildur, it could have last too lond so I abdicated to my heir... but all the artifacts were not passed onto him.
For testing I killed the old guy with console while playong the yougner one, but the artefacts were passed on to others (or not at all for I could not find them all, but with 365 years old, there are many heirs...)

So I Wonder if we could make the artifacts be passed on at abdication...

**Comment by Lonhaldar** [comment]
It should be possible quite easily i suppose. Needs to add some lines in the abdication events by the way, but why not?

**Comment by Lonhaldar** [comment]
Fixed!
