### ISSUE TITLE
Add new Stonefoot kingdom 

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#124]
Reminder to add new dwarven Stonefoot kingdom of around 2 provinces near Nurad/Khand

**Comment by Rigmored** [comment]
Added all files but the provinces don't seem to work, they only show up with noculture and noreligion. 
Never had an issue like this when building the map before, seems anything I add after 810 fails

All files are okay though

**Comment by RiccoPT** [comment]
Stonefoot kingdom working know I made some changes i hope you don´t mind
