### ISSUE TITLE
Should we add Tauriel?

### ISSUE THREAD

**Issue by Chris1993** [Middle-Earth-Project-Team/mod#125]
As a lowborn character at Thranduil's court

**Comment by Rigmored** [comment]
Sure :)

**Comment by Chris1993** [comment]
Added Tauriel at Thranduil's court
Friends: Legolas
Rivals: Thranduil 
Traits: Elf, Agile, Proud, Fair, Trained Elf

![ck2_1](https://cloud.githubusercontent.com/assets/9638717/5678115/3af66cfe-97ef-11e4-82ab-cc0a6efbe5ee.png)

**Comment by Rigmored** [comment]
Btw, I noticed adding portraits slows the mod down a lot, could they be optimised somehow?

**Comment by Lonhaldar** [comment]
Certainly. I need to rework most of them entirely i suppose. They're a lot of duplicates i can reduce i think. 
My problem for now is that for a weird reason my alpha channels in my .dds are broken. certainly a wrong thing in my save properties in Photoshop, but i can't find out which. But at least, i can try to reduce the size of the portraits folder.

**Comment by Rigmored** [comment]
Are you using DXT5 ARGB interpolated alpha?

**Comment by Lonhaldar** [comment]
No i was in DXT3 ARGB explicit alpha. Certainly the wrong thing ^^

**Comment by 6NGB** [comment]
Explicit alpha is the setting I use for icons and it seems ok.
Are TGAs allowed in portraits? Photoshop has internal TGA support, probably it will encode these better.
