### ISSUE TITLE
Flags messed up

### ISSUE THREAD

**Issue by Chris1993** [Middle-Earth-Project-Team/mod#126]
Somebody has recently added new titles without creating proper flags. Now all the flags are messed up

**Comment by Rigmored** [comment]
Uploaded some placeholder flags

**Comment by Lonhaldar** [comment]
Did you added placeholders flags for all the titles? (counties+duchy+kingdom levels?)

**Comment by Rigmored** [comment]
I added 5 titles iirc, k_stonefoot, d_stonefoot, c_stonefoot1, c_stonefoot2 and k_dunland, added all 5 placeholders

**Comment by Lonhaldar** [comment]
I still have some mess with the flags, which titles were added recently?

**Comment by Rigmored** [comment]
With your new flags it works fine for me

**Comment by Lonhaldar** [comment]
Well i've got some bad flags for territories of orcs culture (including angmar), seems that they're creating ingame, like the muslims one, maybe it's normal?

**Comment by Lonhaldar** [comment]
Edit : it came from religions.txt --> in the religion_group_melkor, we had : 
"has_coa_on_barony_only = no"
instead of 
"has_coa_on_barony_only = yes"

Fixed it!

**Comment by Rigmored** [comment]
Oh yea, wasn't a bug, did that on purpose, planning on adding the new Orc CoAs soon, doesn't make sense to see Orc Moria with the flag of Durin etc, same with spiders, wights, etc

**Comment by Lonhaldar** [comment]
Ok, No problem for me !
