### ISSUE TITLE
Restructuring of Enedwaith - progress

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#131]
I have restructured the Enedwaith area in de jure territories. 

There is now a new duchy of Cairill between Gwathlo and Angren

The dejure duchy of Dunland is now split into Nan Laegrim and Emyn Hithui, Ar-Dunland and Fer-Dunland when held by a Dunlending. These 2 duchies make up the de jure kingdom of Emyn Hithui, which is called Dunland when held by a Dunlending. 

The original duchy of Dunland is now a titular tribal title like those held by tribes in vanilla CK2.

There is a new kingdom of Angren which is the duchies of Angren and Isenmarch.

The old kingdom of Enedwaith is now called Morbet and is Gwathlo, Morbet and Cairill.

This is all part of the new empire of Enedhwaith (previously Isenflow), which now also comprises Eregion.

Here are pics of de jure maps for clarity:
Duchies:
![ck2_7](https://cloud.githubusercontent.com/assets/9249948/5696150/e4746dae-99ba-11e4-99ab-cd5d894486de.png)
Kingdoms:
![ck2_5](https://cloud.githubusercontent.com/assets/9249948/5696153/f39c8a3c-99ba-11e4-964b-b31f842baa12.png)
Empires:
![ck2_6](https://cloud.githubusercontent.com/assets/9249948/5696151/ed3cdeda-99ba-11e4-80df-ecb47a6e255f.png)

Reasons:
- Make playing in this area more interesting
- More depth
- Smaller duchies
- Better de jure empire map

Please let me know what you think

**Comment by Chris1993** [comment]
I like it very much, now Enedwaith is really more interesting

**Comment by Lonhaldar** [comment]
looks really good!
In a previous build, we made Rohan part of this de jure empire, to prevent Gondor to claim this land. How will we simulate it now?

**Comment by Rigmored** [comment]
Make a new de jure empire with Vales of Anduin and Rohan?

**Comment by Lonhaldar** [comment]
Yeah, seems to be a good option, an empire of "Isen vale" with the former and actual lands of the Eothed/rohirrim!

**Comment by Rigmored** [comment]
Isenvale wouldn't make sense, perhaps Empire of Eotheod, or of Anduin?

**Comment by Lonhaldar** [comment]
Yeah i wanted to say Anduin, sorry ^^

-------- Message d'origine --------
De : Redit <notifications@github.com> 
Date :14/01/2015  17:34  (GMT+01:00) 
A : Middle-Earth-Project-Team/mod <mod@noreply.github.com> 
Cc : Lonhaldar <antoine@longuet.org> 
Objet : Re: [mod] Restructuring of Enedwaith - progress (#131) 

Isenvale wouldn't make sense, perhaps Empire of Eotheod, or of Anduin?

**Comment by Chris1993** [comment]
PS: Be careful, I'f I remember well, there where some events/decision for Saruman that included the existence of d_dunland, so there could be problem with the new titles set ;)

**Comment by Rigmored** [comment]
Dunland is still d_dunland for now, as they have a titular tribal dukedom

**Comment by Lonhaldar** [comment]
And we can change to k_dunland in the files of the Saruman's events if necessary by the way!

**Comment by Rigmored** [comment]
Perhaps add condition for both? k_dunland doesn't exist at start but will probably be created by AI

**Comment by Chris1993** [comment]
Or add the condition culture = culture_dunlanding so that all the Dunland peoples of lower enedwaith (those from Isenmarch too) will join the war
