### ISSUE TITLE
Flags required

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#135]
The following titles require new flags, currently they placeholders/copies of other titles

- e_anduin (eotheod)
- k_angren
- k_dunland
- k_stonefoot
- d_dunland_north (nan leaglin)
- d_dunland_south (emyn hithlui)
- d_cairill
- d_stonefoot
- c_azanulbizar
- c_stonefoot1
- c_stonefoot2

I also plan on adding a Kingdom of Daoine, but it's not in yet

**Comment by Lonhaldar** [comment]
Will make them if you're ok ;)

**Comment by Rigmored** [comment]
Be my guest :)

**Comment by Lonhaldar** [comment]
Done and merged! You can see them in the forum ;)
