### ISSUE TITLE
Kokutos Bug List 

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#138]
"With the wilderness portraits, specifically I mean that sometimes a character's portrait (a character that isn't wilderness) will turn into wilderness for some unknown reason. Or that their spouse will do that (again even if the spouse is not wilderness), the cause is unknown to me. 

The character errors at this time which I am aware of first include the members of the former Royal family of Rhovanion who then become the Eotheod. Specifically, these Eotheod have been stuck as having 'noculture' rather than a proper Eotheod or Rohirrim culture. So for anyone who chooses to play in that time period, things are a bit odd. 

Next would be some of the events that take place during the war of the Ring. I would like to suggest that the war of the ring even chain have a check put into the front, at it will only start if Frodo is in existence and has the ring. Otherwise, it is to not take place. This is because it seems to activate in part, some way or another no matter what time period it is in. Not the complete event chain, but it seems parts of it may activate for unknown reasons. 

It is possible to see the flag triggers when looking at a save file from eras earlier than the war of the ring.  

Furthermore, the heirs of Isildur have a error in some of the characters. For example, character ID 2034, Arathorn I son of Arassuil seems to be married to a man from a different era for unknown reasons, a dead man I might add. Next is character ID 2121, this character appears to spawn at a set time even when no heir of Isildur character is actually there to sire it. 

Next are the children of the last king of Cardolan, ID 2090. It seems strange that three of his children are suddenly marked as heirs of Isildur. This screws up the Isildur family tree as well. "

**Comment by Lonhaldar** [comment]
- Removed the wife of Arathorn I
- Fixed the dynasties for the children of the last king of cardlan

I didn't unerstand the bug with the character 2121, but i don't know why we've got another branch of the Isildurionath family at this time ( another son of Arathorn I it seems)

I let you check the other things ;)
