### ISSUE TITLE
Crash loading WoTR bookmark

### ISSUE THREAD

**Issue by Lonhaldar** [Middle-Earth-Project-Team/mod#139]
I've got a crash when loading the WoTR bookmark. It doesn't seems to come from my files at far as i searched, anyone else experienced that?

**Comment by Rigmored** [comment]
No problem for me

**Comment by Lonhaldar** [comment]
Ok, will reinstall completely from the committed files

**Comment by Rigmored** [comment]
I now have issues starting all bookmarks, very strange

**Comment by 6NGB** [comment]
No problems with all 3 bookmarks for me.

**Comment by 6NGB** [comment]
Hmm, on my desktop i have the CTD on the WotR bookmark (the others are OK). I'm researching it...

**Comment by 6NGB** [comment]
OK, after experimenting with some different combos of earlier commits, versions, DLCs, I think I got a clue: if the WotR bookmark is set on 11359.12.31 or earlier -- the geme is OK and there is no CTD. Starting from 11360.1.1 and later -- it crashes. There are lots of events on 11360.1.1. Deaths, births, changes in titles. At least one of them is causing the game to CTD, imo. I confirm this for the latest commit, version and WoL enabled. The problem must be in the history files somewhere.

**Comment by 6NGB** [comment]
The above is valid also in case you set the start date manually. If a game is started before 11359.12.31 it is OK. It won't crash on 11360.1.1 but will keep going fine. If a start on 11360.1.1 or later is selected, no matter if manual or bookmark -- the game will CTD on startup.

**Comment by Rigmored** [comment]
This only happened in the last few days, so it must have been added very recently

**Comment by 6NGB** [comment]
I tried with older versions, the oldest being the f7a45a (7 days ago), and the problem is present.

**Comment by Lonhaldar** [comment]
Can't find out why we've got this crash for now. Because we needs to add back more events, because some are triggered but not present in the build?

**Comment by Rigmored** [comment]
It must be a history error

**Comment by Lonhaldar** [comment]
Fixed, the error came from the MEP_titles_fixes file. I removed it for now.
