### ISSUE TITLE
Map objects Position

### ISSUE THREAD

**Issue by RiccoPT** [Middle-Earth-Project-Team/mod#144]
There is a need to organize the positions os the map objects in each province

**Comment by RiccoPT** [comment]
I'm currently organizing this
Done:
Sea and tiver provinces
Black numenor kingdoms

**Comment by Lonhaldar** [comment]
Ok, i can help you to improve that, just tell me when you want me to work on some areas.

**Comment by Rigmored** [comment]
We can also make the councillor, soldier, ship and town avatars smaller a I originally planned to do, so they fit better in the Middle Earth map scale and fit our much smaller provinces

**Comment by RiccoPT** [comment]
This i Dont know how to do need to check this out
Em 08/04/2015 13:40, "Redit" <notifications@github.com> escreveu:

**Comment by Rigmored** [comment]
In interface/avatars (check vanilla ck2 file) there is a scale entry, lowering it will decrease the size of the models. So most have a scale of 1.0f, changing it to 0.5f will half its size

**Comment by Lonhaldar** [comment]
I fixed all the positions of the objects. Just needs some ports!
