### ISSUE TITLE
Missing traits

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#78]
Narya (Cirdan's and Gandalf's Ring), 5 Dwarven Rings and 7 (?) of the Nine appear to be missing... Same with several palantir.

**Comment by Lonhaldar** [comment]
Maybe a problem with the encodage of the graphic files, can you try to remake them (with the same icons), to see if it came from me?

**Comment by Rigmored** [comment]
They are all working now except the 5 Dwarf-rings not held by Sauron, or are they not intended to be in the game still at War of Ring?

I fixed problem with Akorahil ring gfx also

**Comment by Lonhaldar** [comment]
well they were'nt really created, only one "dwarven ring" trait was created, so Sauron can't hold 5 of this one at the same time i believe.
Can you have a look on the "Black Serpent" trait too? It doesn't seems to work with me.

**Comment by Rigmored** [comment]
Yep will do now, btw I noticed Murazors portrait only seems to work if I play as him, otherwise he has an old Nazgul portrait

**Comment by Lonhaldar** [comment]
Yeah i noticed it, especially during the WoTR, in the Fall of Arnor it seems to work normally, in my tests at least. It should be quite simple to fix that i think, certainly something in the portraits_properties

**Comment by Rigmored** [comment]
Very odd, I can't get it working either, I tried renaming it but same issue. It seems to be a problem with the .dds as the coding works fine...

Some very strange new bugs, I think linked to GitHub perhaps

**Comment by Lonhaldar** [comment]
Hmmmm. That's weird. Maybe we reached the limit of traits? ^^
