### ISSUE TITLE
If Witch King becomes incapable

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#89]
He never gets better

**Comment by Lonhaldar** [comment]
Strange, i fixed it in the health events normally, don't know if it's triggered in another events?
A simple event can work for this i suppose, but will slow down the mod i think : the incapable trait will come back, and the event to remove it will fire again and again.

**Comment by Rigmored** [comment]
Maybe add decision for incapable of certain culture? If we can set AI to always do it, or make it free with a small bonus like 5 prestige

**Comment by Lonhaldar** [comment]
- Added potential conditions to the trait "incapable", who'll remove the cultures : culture_wight, culture_dragons, culture_balrog, culture_group_wilderness, culture_group_eru.
- Added an event to remove this trait for members of these cultures if they gain it by event/console.
