### ISSUE TITLE
Arthedain must be completely controlled

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#94]
Bug with the form Arnor decision for Arthedain

Kingdom can never be completely controlled, I'm guessing a bug in landed_titles for a county or barony that no longer exists but is still present

**Comment by Lonhaldar** [comment]
Maybe. The Validator says something about landed_titles?

**Comment by Lonhaldar** [comment]
Fixed. there was some errors like titleprefix instead of title_prefix !
