### ISSUE TITLE
Gwaith-i-mirdain events stall

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#97]
Problem with events, from forum and moddb:
- "Managed to start the event chain for rebuilding the Gwaith but it stalls when you click to assemble the artists."
- "I'm unsure if this is a bug but I selected to reform the Gwaith-i-mirdan (The Eregion smiths) and I got several events up to the "Time of gather the Craftsmen". Then, nothing happened, I've been waiting for several years now, still nothing sadly :/"

**Comment by Lonhaldar** [comment]
Will fix that!
